### ISSUE TITLE
Feature Request - Shared Spaces

### ISSUE THREAD

**Issue by Valiantiam** [range-of-motion/budget#207]
**Expected behavior**

Spaces are great, but should be expanded to "invite" others to join your space so that they can contribute transactions at a minimum. You should be able to subsequently manage their access to your spaces with an easy ability to remove or add additional users as needed. An invite could include a link to registration, or if an account already exists, an "accept" button that joins them to your space you invited them to. Spaces would need their own management page as well then so you can easily tell who has access. Logs/activity history should also indicate the user who added transactions or made additional changes. 

In addition, this could be expanded to have a simple ACL system for users you share your space(s) with that lets you dish out permissions on only viewing, being able to edit transactions, tags, budgets, etc. 

**Current behavior**

Spaces only provide you a way to individually separate expenses.

**Comment by range-of-motion** [comment]
Thanks for suggesting this, I will attempt to work on this in the next update.

**Comment by range-of-motion** [comment]
The PRs for this issue will be split, to keep the changes relatively small.

* #211, for invitations to spaces
* Another one, for the creation of spaces

**Comment by range-of-motion** [comment]
Alright, up until this point I've made it so that you can create spaces, and invite others to join your space(s). 

There are probably many more features you would want regarding spaces, such as inviting others that don't have an account yet, or kicking people from your space.

However, I have no clue which of these ideas are the most populair, and I see myself blowing up the scope of this. Therefor I will consider this issue "done", and close it. If there are any specific requests, like the ones I mentioned above, please let me know in a separate issue.
