### ISSUE TITLE
Missing currency SGD

### ISSUE THREAD

**Issue by assman** [range-of-motion/budget#249]
No provision for SGD

**Comment by range-of-motion** [comment]
I did add the SGD in the latest release (v0.8.0), however the currency dropdown on the registration page is very confusing, since the SGD has the same symbol as the USD, for example.

I will try and improve the dropdown for currencies to make it more clear.

**Comment by range-of-motion** [comment]
I tried to clarify the dropdown for currencies by changing the following.

* Showing the names of the currencies next to their symbols
* Turned the input into a regular `<select>` element because that it seems better for usability

In the future I'd like to implement some sort of onboarding process that moves these preferences to a separate step, but for now I think the aforementioned changes are sufficient.

**Comment by assman** [comment]
Thank you

**Comment by range-of-motion** [comment]
Done in #250.
