### ISSUE TITLE
Can't seed if we run composer install --no-dev

### ISSUE THREAD

**Issue by HenocKA** [range-of-motion/budget#8]
According to the readme, when we seed database after a 'composer install --no-dev', we have this error :  'Class 'Faker\Factory' not found'. 
Missing 'fzaninotto/faker' package

**Comment by range-of-motion** [comment]
This is because seeding should be used in development, not in production. I understand that there's a bit of confusion because the README instructs you to install dependencies like you're in a production environment, but then goes on to tell you that you should use seeders.

I'll think about it and let you know what I decide on. If anyone has any ideas, do share 👍

**Comment by dsone** [comment]
Buuut if we're not "supposed" to use seeding, we can't get the currencies into the database. Yet you do have to use seeding, just manually in this case (`php artisan db:seed --class=CurrenciesTableSeeder`) to not trigger the User seeder that is in need of the Faker package.

The installation process of budget is made unnecessary annoying this way and gives a bad first impression.

**Comment by range-of-motion** [comment]
This issue has been resolved in 3b5eb7c4af6ea4cb68e14cafa80e8e129598ce45.
